// 젠킨스 파이프라인 플러그인을 호출하기 위한 블록
pipeline {
	// 파이프라인을 실행하고 싶은 위치 정의
	agent none
	// gitlab의 소스를 jenkins 디렉토리로 내려받을 시
	// skipDefaultCheckout(true)일 경우 내려받는 프로세스 skip
	// skipDefaultCheckout(false)일 경우 gitlab 소스 체크
	options { skipDefaultCheckout(true) }
	// stage의 모음
	stages {
		// 실제 작업이 수행되는 블록
		// 해당 stage 명으로 jenkins 화면에 표시된다
		stage('Gradle test') {
        steps {
            script {
                try {
                    sh 'chmod 755 ./gradlew'
                    sh 'docker-compose -f docker-compose.yml down'
                    sh 'docker-compose -f docker-compose.yml up -d db migration'
                    sh './gradlew clean build'
                } catch (e) {
                    sh 'echo Gradle test Fail!!!'
                    slackSend (channel: '#jenkins-test', color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
                }
            }
        }
    }
        stage('Docker build') {
            agent any
            steps {
                // front-end 및 back-end dockerfile 실행을 통해 image 생성
                // -t : 이미지 이름과 tag 설정, 만약 이미지 이름만 설정하면 latest로 설정됨
                sh 'docker build -t kbi_front:latest ./exec/project_frontend'
                sh 'docker build -t kbi_back:latest ./exec/project_backend'
            }
        }
        stage('Docker run') {
            agent any
            steps {
				// 현재 동작중인 컨테이너 중 kbi_front의 이름을 가진 컨테이너를 stop
				sh 'docker ps -f name=kbi_front -q \
					| xargs --no-run-if-empty docker container stop'
				// 현재 동작중인 컨테이너 중_ kbi_back의 이름을 가진 컨테이너를 stop
				sh 'docker ps -f name=kbi_back -q \
					| xargs --no-run-if-empty docker container stop'
				// kbi_front의 이름을 가진 컨테이너를 삭제
				sh 'docker container ls -a -f name=kbi_front -q \
					| xargs -r docker container rm'
				// kbi_back의 이름을 가진 컨테이너를 _삭제
				sh 'docker container ls -a -f name=kbi_back -q \
					| xargs -r docker container rm'
				// docker image build 시 기존에 존재하던 이미지는
				// dangling 상태가 되기 때문에 이미지를 일괄 삭제
				sh 'docker images -f dangling=true && \
					docker rmi $(docker images -f "dangling=true" -q)'
				// docker container 실행
				// 하나의 docker network에 연결하여 통신이 가능하도록 설정
				sh 'docker run -d --name kbi_front \
					-p 80:80 \
					-p 443:443 \
					-v /var/jenkins_home/workspace/kbi_project/sslkey:/var/jenkins_home/workspace/kbi_project/sslkey \
					-e TZ=Asia/Seoul \
					--network kbi_net \
					kbi_front:latest'
				sh 'docker run -d --name kbi_back \
					-v kbi-vol:/kbi_project \
					-e TZ=Asia/Seoul \
					--network kbi_net \
					kbi_back:latest'	
			}
		}
	}
}