version: '3.7'

services:
        db:
                image: mysql:8.0.28
                container_name: mysql-kbi
                ports:
                        - '3308:3306' # 접근 포트 설정
                environment:
                        - MYSQL_ROOT_PASSWORD=dnjswns1!
                        - TZ=Asia/Seoul
                restart: unless-stopped
                command:
                        - --character-set-server=utf8mb4
                        - --collation-server=utf8mb4_unicode_ci
                volumes:
                        - /usr/shared/data/kbi-mysql:/var/lib/mysql
                networks: 
                        - kbi_net
networks:
        kbi_net:
                external: true